FROM rust:buster as builder

WORKDIR /build
COPY . .
RUN cargo build --release

FROM debian:buster-slim

WORKDIR /app

RUN apt-get update && apt install -y libpq-dev openssl ca-certificates
COPY --from=builder /build/target/release/api_run .
COPY prod_zip/raw_*.zip /app/raw_input/


EXPOSE 8080

VOLUME /app/raw_input

CMD ["./api_run"]
