{{ if eq .Values.env "prod" }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
  namespace: {{ $.Release.Namespace }}
spec:
  dnsNames:
  - "defispring-mainnet.zkx.fi"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-cloudflare
  secretName: certificate
  usages:
  - digital signature
  - key encipherment
{{ end }}