{{ if eq $.Values.env "prod" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: defispring-mainnet
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: defispring-mainnet
  template:
    metadata:
      labels:
        app: defispring-mainnet
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      imagePullSecrets:
        - name: dockerhub
      containers:
      - image: zkxteam/defispring:{{ .Values.commit_hash}}
        imagePullPolicy: Always
        name: defispring-mainnet
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
      nodeSelector:
        role: stateless
---
apiVersion: v1
kind: Service
metadata:
  name: defispring-mainnet
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    app: defispring-mainnet
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: defispring-mainnet
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - defispring-mainnet.zkx.fi
    secretName: certificate
  rules:
  - host: defispring-mainnet.zkx.fi
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: defispring-mainnet
              port:
                number: 80
{{ end }}